version: '3.8'

services:
  home_tv_database:
    image: postgres:latest
    container_name: home_tv_database
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hometv
